### ISSUE TITLE
Create a web UI for the hello world app

### ISSUE THREAD

**Issue by zpallin** [YYZ-Engine/yyz-engine#16]
Let's discuss this first and plan out our strategy.

What I want to see implemented is a web interface that leverages javascript animations, a solid color palette, and a "single webpage" type of architecture (where there is only one loadable page and all other views load dynamically).

This app should not call new, internal functions for, but rather should leverage the existing API where possible. 

Before beginning work, let's have you propose the following in this issue:
1. a color palette
2. images to represent each day of the week and any other image set
3. any other ideas we can have to make this site look entertaining

**Comment by ychoy** [comment]
Perhaps we can use this color palette: http://colorpalettes.net/color-palette-3899/

Images for /api/hello and /api/hello/(day routes: 
- Good Morning: https://unsplash.com/photos/JuP0ZG0UNi0
- Good Afternoon: https://unsplash.com/photos/sYffw0LNr7s
- Good Evening: https://unsplash.com/photos/qkfxBc2NQ18

For /api/world route , maybe there is a world map and it zooms into the country of the user

**Comment by zpallin** [comment]
Dope af. I'm for it all. Let's make the /api/world route idea a separate ticket. Want to make that github issue?
